package com.crossover.techtrial.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.*;

import javax.persistence.*;
import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * DailyElectricity is responsible for daily electricity generated by a Panel
 *
 */
@Entity
@Table(name = "daily_electricity")
@Data
@NoArgsConstructor
public class DailyElectricity implements Serializable {
    private static final long serialVersionUID = 1505984390621325049L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @JsonIgnore
    @ManyToOne
    @JoinColumn(name = "panel_id", referencedColumnName = "id")
    private Panel panel;

    @Column(name = "generated_electricity_sum")
    private Long generatedElectricitySum;

    @Column(name = "generated_electricity_min")
    private Long generatedElectricityMin;

    @Column(name = "generated_electricity_max")
    private Long generatedElectricityMax;

    @Column(name = "generated_electricity_average")
    private Double generatedElectricityAverage;

    @Column(name = "reading_at")
    private LocalDateTime readingAt;

    public DailyElectricity(Panel panel, Long generatedElectricitySum, Long generatedElectricityMin,
                            Long generatedElectricityMax, Double generatedElectricityAverage, LocalDateTime readingAt) {
        this.panel = panel;
        this.generatedElectricitySum = generatedElectricitySum;
        this.generatedElectricityMin = generatedElectricityMin;
        this.generatedElectricityMax = generatedElectricityMax;
        this.generatedElectricityAverage = generatedElectricityAverage;
        this.readingAt = readingAt;
    }
}
